# Generated by Django 6.0.4 on 2026-05-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_entrega', models.DateTimeField()),
                ('data_finalizada', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['data_criacao'],
            },
        ),
        migrations.DeleteModel(
            name='Listag',
        ),
    ]
